### ISSUE TITLE
Add a possibility to remove an image

### ISSUE THREAD

**Issue by ramendik** [cyberorg/live-fat-stick#13]
One could create and try a number of images then decide some are not needed.

Now one can, of course, just clear the flash drive and try again, or else comment them out in syslinux.cfg.

But I think it might be more user-friendly to add a feature (or a separate script, perhaps) to remoive any of the images. It could also delete the kernel/initrd and optionally the image itself from the flash drive.

Thanks! (And this is an absolutely wonderful tool, btw)

**Comment by cyberorg** [comment]
Thanks for the suggestion, however as you mention it is easy to remove it by editing syslinux.cfg and removing the image, so I would not be working on this, I would be happy to receive patches if you work it out :)
