### ISSUE TITLE
No free space at root partiotion

### ISSUE THREAD

**Issue by DAP-DarkneSS** [cyberorg/live-fat-stick#15]
I've tried openSUSE-Tumbleweed-KDE-Live-x86_64-Snapshot20150423-Media.iso at 16 GByte flash. Gui version did nothing, cli version made boot, ldlinux.sys and live-fat-stick but didn't copy an image. So I did it.
Image is booted fine but only ½ GByte is offered for user, it disappears too fast and finally X freezes. I've tried to install some packages (100 MBytes may be) three times :(

**Comment by cyberorg** [comment]
You cannot install packages in "live"(-suse) mode, if you want more space available use -isohybrid mode. Live mode will only show available RAM as that is where the OS is run from.

Not sure about your other issues, try freshly formatted usb stick and open new bug report with output on the terminal when you run live-usb-gi and live-fat-stick...

**Comment by DAP-DarkneSS** [comment]
I have 7 GBytes of RAM anyway. If iso is burned in usual way much more  
than ½ GBytes of space is available. So have I to make iso hybrid and burn  
it?

**Comment by cyberorg** [comment]
live-fat-stick --help
For isohybrid   : live-fat-stick --isohybrid /path/to/isohybridimage.iso /dev/sdX

**Comment by cyberorg** [comment]
live-fat-stick --help
For isohybrid   : live-fat-stick --isohybrid /path/to/isohybridimage.iso /dev/sdX
