### ISSUE TITLE
`live-fat-stick --isohybrid` makes nothing

### ISSUE THREAD

**Issue by DAP-DarkneSS** [cyberorg/live-fat-stick#16]
As you requested the stick had been formatted.

%sudo live-fat-stick --isohybrid /mnt/E-Install/Soft/OS\ +\ Live\ CD/openSUSE-Tumbleweed-KDE-Live-x86_64-Snapshot20150423-Media.iso /dev/sdd
Please make sure the following information is correct:
iso name: openSUSE-Tumbleweed-KDE-Live-x86_64-Snapshot20150423-Media.iso distro: isohybrid stick device: /dev/sdd
stick uuid: /dev/disk/by-uuid/2014-10-27-16-28-41-00 stick partition: 
continue ? [y/n]? y
dd_rescue: (info): Using softbs=4096.0kiB, hardbs=4.0kiB
dd_rescue: (info): expect to copy 962368.0kiB from /tmp/tmp.3UyF8zdVPb
dd_rescue: (info): ipos:    958464.0k, opos:    958464.0k, xferd:    958464.0k
                   errs:      0, errxfer:         0.0k, succxfer:    958464.0k
             +curr.rate:    28158kB/s, avg.rate:    25555kB/s, avg.load: 13.2%
             >----------------------------------------.<  99%  ETA:  0:00:00 
dd_rescue: (info): read /tmp/tmp.3UyF8zdVPb (962368.0kiB): EOF
dd_rescue: (info): Summary for /tmp/tmp.3UyF8zdVPb -> +
dd_rescue: (info): ipos:    962368.0k, opos:    962368.0k, xferd:    962368.0k
                   errs:      0, errxfer:         0.0k, succxfer:    962368.0k
             +curr.rate:    27624kB/s, avg.rate:    25557kB/s, avg.load: 13.2%
             >-----------------------------------------< 100%  TOT:  0:00:38 
cleaning up
Your bootable usb stick is now ready
have a lot of fun...

**Comment by cyberorg** [comment]
live-fat-stick --isohybrid /mnt/E-Install/Soft/OS\ +\ Live\ CD/openSUSE-Tumbleweed-KDE-Live-x86_64-Snapshot20150423-Media.iso /dev/sdd

That just runs:

dd_rescue /mnt/E-Install/Soft/OS\ +\ Live\ CD/openSUSE-Tumbleweed-KDE-Live-x86_64-Snapshot20150423-Media.iso /dev/sdd

If the USB stick is not bootable by running the above command, try : 

dd if=/mnt/E-Install/Soft/OS\ +\ Live\ CD/openSUSE-Tumbleweed-KDE-Live-x86_64-Snapshot20150423-Media.iso of=/dev/sdd bs=4M

If that also does not make the stick bootable may be the iso is not downloaded properly or there is some other issue with the image, you'll have to report it to openSUSE bug tracker.

If the dd_rescue command makes the image bootable and not live-fat-stick command then send output with sh -x /usr/bin/live-fat-stick --isohybrid /mnt/E-Install/Soft/OS\ +\ Live\ CD/openSUSE-Tumbleweed-KDE-Live-x86_64-Snapshot20150423-Media.iso /dev/sdd

**Comment by DAP-DarkneSS** [comment]
`dd_rescue /mnt/E-Install/Soft/OS\ +\ Live\  
CD/openSUSE-Tumbleweed-KDE-Live-x86_64-Snapshot20150423-Media.iso  
/dev/sdd` made it bootable. live-fat-stick made nothing: the stick was  
blank.

%sudo sh -x /usr/bin/live-fat-stick --isohybrid /mnt/E-Install/Soft/OS\ +\  
Live\ CD/openSUSE-Tumbleweed-KDE-Live-x86_64-Snapshot20150423-Media.iso  
/dev/sdd
root's password:
+  
PATH=/usr/sbin:/usr/bin:/sbin:/bin:/sbin:/usr/sbin:/usr/local/sbin:/usr/local/bin:/usr/bin:/bin
+ ionice -c3 -p11063
+ trap 'clean_up user_killed' SIGINT SIGTERM
++ id -u
+ [[ 0 != 0 ]]
+ '[' 3 -gt 2 ']'
+ case $1 in
+ distroname=isohybrid
+ shift
+ '[' 2 -gt 2 ']'
+ '[' '/mnt/E-Install/Soft/OS + Live  
CD/openSUSE-Tumbleweed-KDE-Live-x86_64-Snapshot20150423-Media.iso' == -h  
-o '/mnt/E-Install/Soft/OS + Live  
CD/openSUSE-Tumbleweed-KDE-Live-x86_64-Snapshot20150423-Media.iso' ==  
--help ']'
+ '[' '/mnt/E-Install/Soft/OS + Live  
CD/openSUSE-Tumbleweed-KDE-Live-x86_64-Snapshot20150423-Media.iso' == -l  
-o '/mnt/E-Install/Soft/OS + Live  
CD/openSUSE-Tumbleweed-KDE-Live-x86_64-Snapshot20150423-Media.iso' ==  
--list ']'
+ [[ x/mnt/E-Install/Soft/OS + Live  
CD/openSUSE-Tumbleweed-KDE-Live-x86_64-Snapshot20150423-Media.iso == x ]]
+ [[ x/dev/sdd == x ]]
+ [[ ! -e /usr/bin/syslinux ]]
+ [[ ! -e /usr/bin/fuseiso ]]
+ [[ ! -e /mnt/E-Install/Soft/OS + Live  
CD/openSUSE-Tumbleweed-KDE-Live-x86_64-Snapshot20150423-Media.iso ]]
+ [[ ! -e /dev/sdd ]]
+ distroname=isohybrid
+ [[ isohybrid != suse ]]
+ [[ isohybrid != ubuntu ]]
+ [[ isohybrid != fedora ]]
+ [[ isohybrid != isohybrid ]]
++ mktemp -d
+ isomount=/tmp/tmp.WBnPUzfk6h
++ mktemp
+ iso_symlink=/tmp/tmp.NjVHc6LRcK
+ rm /tmp/tmp.NjVHc6LRcK
+ ln -s '/mnt/E-Install/Soft/OS + Live  
CD/openSUSE-Tumbleweed-KDE-Live-x86_64-Snapshot20150423-Media.iso'  
/tmp/tmp.NjVHc6LRcK
++ mktemp -d
+ stickmount=/tmp/tmp.tUCM56WleL
++ echo /dev/sdd
++ sed 's/[0-9]*//g'
+ stickdevice=/dev/sdd
++ basename /dev/sdd
+ stickbase=sdd
++ basename '/mnt/E-Install/Soft/OS + Live  
CD/openSUSE-Tumbleweed-KDE-Live-x86_64-Snapshot20150423-Media.iso'
+ isoname=openSUSE-Tumbleweed-KDE-Live-x86_64-Snapshot20150423-Media.iso
++ echo openSUSE-Tumbleweed-KDE-Live-x86_64-Snapshot20150423-Media.iso
++ cut -d - -f 1,2,3
+ isonameshort=openSUSE-Tumbleweed-KDE
++ blkid -s UUID -o value /dev/sdd
+ stickuuid=2015-04-23-22-13-50-00
++ basename /dev/sdd
++ sed 's/[a-z]*//g'
+ stickpart=
+ syslinuxpath=/tmp/tmp.tUCM56WleL/boot/syslinux
+ stickdevpart=/dev/sdd
+ liveusbgui=/tmp/liveusbgui
+ benice='nice ionice -c3'
+ [[ ! -h /dev/disk/by-uuid/2015-04-23-22-13-50-00 ]]
+ echo openSUSE-Tumbleweed-KDE-Live-x86_64-Snapshot20150423-Media.iso
+ grep -qi Li-f-e
+ echo 'Please make sure the following information is correct:'
Please make sure the following information is correct:
+ echo 'iso name:  
openSUSE-Tumbleweed-KDE-Live-x86_64-Snapshot20150423-Media.iso distro:  
isohybrid stick device: /dev/sdd'
iso name: openSUSE-Tumbleweed-KDE-Live-x86_64-Snapshot20150423-Media.iso  
distro: isohybrid stick device: /dev/sdd
+ echo 'stick uuid: /dev/disk/by-uuid/2015-04-23-22-13-50-00 stick  
partition: '
stick uuid: /dev/disk/by-uuid/2015-04-23-22-13-50-00 stick partition:
+ [[ ! -f /tmp/liveusbgui ]]
+ are_you_sure 'continue ?' y n
+ echo -n 'continue ? [y/n]? '
continue ? [y/n]? + true
+ read answer
y
+ case $answer in
+ answer=y
+ break
+ [[ isohybrid == isohybrid ]]
+ try_cp_with_progress /mnt/E-Install/Soft/OS + Live  
CD/openSUSE-Tumbleweed-KDE-Live-x86_64-Snapshot20150423-Media.iso /dev/sdd
+ sync
+ '[' -x /usr/bin/dd_rescue ']'
+ nice ionice -c3 dd_rescue -A -b 4M -y 4M /tmp/tmp.NjVHc6LRcK +
dd_rescue: (info): Using softbs=4096.0kiB, hardbs=4.0kiB
dd_rescue: (info): expect to copy 962368.0kiB from /tmp/tmp.NjVHc6LRcK
dd_rescue: (info): ipos:    958464.0k, opos:    958464.0k, xferd:     
958464.0k
                    errs:      0, errxfer:         0.0k, succxfer:     
958464.0k
              +curr.rate:    26539kB/s, avg.rate:    25500kB/s, avg.load:  
13.4%
              >----------------------------------------.<  99%  ETA:   
0:00:00
dd_rescue: (info): read /tmp/tmp.NjVHc6LRcK (962368.0kiB): EOF
dd_rescue: (info): Summary for /tmp/tmp.NjVHc6LRcK -> +
dd_rescue: (info): ipos:    962368.0k, opos:    962368.0k, xferd:     
962368.0k
                    errs:      0, errxfer:         0.0k, succxfer:     
962368.0k
              +curr.rate:    26071kB/s, avg.rate:    25496kB/s, avg.load:  
13.4%
              >-----------------------------------------< 100%  TOT:   
0:00:38
+ clean_up
+ [[ '' == user_killed ]]
+ echo 'cleaning up'
cleaning up
+ umount_everything
+ sync
+ [[ isohybrid != isohybrid ]]
+ echo 'Your bootable usb stick is now ready'
Your bootable usb stick is now ready
+ echo 'have a lot of fun...'
have a lot of fun...
+ [[ -f /tmp/liveusbgui ]]

Nothing again.

**Comment by cyberorg** [comment]
Try the latest commit, if that does not help then get rid of "+" from the path.

**Comment by DAP-DarkneSS** [comment]
By the way isohybrid mode will not leave my stick "live fat", will it? If  
so are there any tips to get true live fat stick with possibility to  
install and remove software?

**Comment by DAP-DarkneSS** [comment]
The latest commit seems to provide a fix, thanks.
