### ISSUE TITLE
bad logic: script goes highwire if iso name has spaces & free space is not on 1st partition

### ISSUE THREAD

**Issue by v-fox** [cyberorg/live-fat-stick#18]
The script seems to do unpredictable stuff, like copying an iso into current directory with mangled name, if its name contains spaces. Inability to use relative paths is quite baffling too.

And I'm not sure if it copies anything into /tmp but it shouldn't. People may be using tmpfs, you know.
Also, a partition for free space should be allocated **before** all others because otherwise Windows® refuses to mount it on plugging (it only mounts the first partition on USB sticks, last time I checked).

**Comment by cyberorg** [comment]
Script does not copy anything in /tmp, just uses it to create symlinks and mountpoints, which are removed on successful completion of the script.

Script does not create any partitions.

Open new bug report with full output of sh -x live-fat-stick....  run to debug iso names with spaces.

**Comment by v-fox** [comment]
What the hell do you mean "it does not create any partitions" ? Isn't it whole damn point of it ?! Well, technically, it's that bad, it only allocates empty space that's redundant for an iso in isohybrid mode. So even that simple thing has to be done manually. But it does it in the wrong place too. It **should** create a partition, the first partition, to fulfil it's purpose of a tool for easy allotment of redundant space. Otherwise, I'm not sure why it even exists, the way it does it it's not only useless but dangerous.

And I don't think you need my assistance to create a file with spaces and run your script. Who the hell knows what it will do if it can't handle even such basic things years after going public ? I think I'll just remove it.

**Comment by cyberorg** [comment]
The script does not create any partition whatsoever, the script only puts iso on the pre-formated vfat stick/usb hdd. As mentioned in README, the script exists to create multi-boot usb sticks from multi distributions, keeping iso intact where possible on sticks formatted with vfat, hope this clears your misconceptions regarding the scope of this tool.

When --isohybrid is used, only dd of the iso to stick is carried out, the partitioning is handled by the distribution, not by this script.

Also this is mentioned in the script:

"# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more
# details."

If you read further in the script you can figure out what the hell it actually does.

Cheers :)

**Comment by v-fox** [comment]
> When --isohybrid is used, only dd of the iso to stick is carried out, the partitioning is handled by the distribution, not by this script.

Then I guess that extra >200MB empty space on my stick wasn't even the result of calculations but a happenstance.

> If you read further in the script you can figure out what the hell it actually does.

Looks like what it does is copying files while breaking their names and destinations since even the only useful thing that has happened was an accident. At least in this mode. I really hope that the real "scope of this tool" handled better than that for the sake of those who would decide to use it not on VMs.

And don't go around citing licenses, It only has purpose if someone would try to call cops on you for unexpectedly formatting HDDs or something which, while not a crime, wouldn't be any less of a major dick move.

**Comment by cyberorg** [comment]
What exactly is the issue you have now?

Partitioning when isohybrid is not handled by this script and never will be.

This script is to use with vfat formatted usb stick, partitioning and formatting have to be done be done before using this script, if something is broken in that respect feel free to report instead of throwing abuses around.

**Comment by v-fox** [comment]
> What exactly is the issue you have now?

That ￬
> Partitioning when isohybrid is not handled by this script and never will be.

 _
> BTW, I haven't come across any distro which has spaces in the iso name yet.

Well, mine is. And I'm not going to change that to accommodate tools with broken name handling. That's a problem, I reported it, the fact that you might not care is another matter. I'm not going to persuade you, that's certainly not my problem.

**Comment by cyberorg** [comment]
Creating bootable usb stick with iso name with spaces is fixed in last commit, if the stick does not boot you can get back with full output of sh -x .... as requested before.
