### ISSUE TITLE
Did not work with Gentoo Live DVD

### ISSUE THREAD

**Issue by mbzadegan** [cyberorg/live-fat-stick#23]
I tried this script to use for [Gentoo Live DVD](http://gentoo.inode.at//releases/amd64/20160514/livedvd-x86-amd64-32ul-20160514.iso) but did not work, Is that a resolve way?

**Comment by cyberorg** [comment]
Gentoo is not supported yet, I will be happy to accept patches, feel free to fork and modify the script to add gentoo.
