### ISSUE TITLE
openSUSE Tumbleweed fails to boot on non-isohybrid with dracut: FATAL: No or empty root= argument

### ISSUE THREAD

**Issue by achaios** [cyberorg/live-fat-stick#25]
I successfully installed the TW rescue iso:
live-grub-stick --suse-persistent openSUSE-Tumbleweed-Rescue-CD-x86_64-20171205.iso /dev/sdc1
But when trying to boot it, the system hang after the error message in the subject.
Same thing happened with live-fat-stick.

**Comment by cyberorg** [comment]
Can't do much here, looks like there is no support for booting from iso image and using image file for persistence as we had before(isofrom_device/isofrom_system and for persistent data kiwi_cowdevice) or the one dracut has(iso-scan as mentioned here https://github.com/haraldh/dracut/blob/master/dracut.cmdline.7.asc#iso-scanfilename)

See and comment on : https://github.com/SUSE/kiwi/issues/470 or open new issue there if you want this feature.

**Comment by cyberorg** [comment]
We'll keep this open to adapt our scripts as per upstream fixes.

**Comment by cyberorg** [comment]
Fixed in https://github.com/cyberorg/live-fat-stick/commit/e794e1b14388519d3ba2199e67837bcb70e1ee9e

Test using images from https://build.opensuse.org/project/show/openSUSE:Factory:Live
