### ISSUE TITLE
i586 install fails

### ISSUE THREAD

**Issue by sboehringer** [cyberorg/live-fat-stick#27]
when booting, x86_64 is accessed for suse images. This is hard coded in the script and breaks i586 installs.

**Comment by cyberorg** [comment]
There is no i586 openSUSE releases since few years so support for that was dropped.

Besides we may be able to support only --isohybrid mode for suse images if there is no resolution to https://github.com/cyberorg/live-fat-stick/issues/25

**Comment by sboehringer** [comment]
The very latest of Tumbleweed is available for i586.
https://software.opensuse.org/distributions/tumbleweed/ports

**Comment by cyberorg** [comment]
Fixed in https://github.com/cyberorg/live-fat-stick/commit/e794e1b14388519d3ba2199e67837bcb70e1ee9e

Test using images from https://build.opensuse.org/project/show/openSUSE:Factory:Live
